1774-ProyectoIntegrador/frontend

- package.json
- pnpm-lock.yaml
- src/components/atoms/CardBeneficios.jsx
- src/components/molecules/BeneficiosSeccion.jsx
- src/utils/beneficiosData.json
- src/utils/iconsMapping.js
- Se añadieron iconos de Material Icons.
- Corrección de estructura y eliminación de elementos duplicados.
- Refactorización de código.
> Beneficios - Actualización y Fix

- src/App.jsx
- src/components/molecules/header/LogoLoginContainer.jsx
- src/components/molecules/header/Navbar.jsx
- src/components/organisms/Header.jsx
- src/components/organisms/header/MenuMobile.jsx
- src/contexts/global.context.jsx
- src/main.jsx
- src/reducers/reducer.js
- src/styles/basics.css
- src/utils/routes.js
- ajustar el archivo de rutas para que traigan el label de una vez
- crear archivo para contextos globales
- crear reducer adelantar configuracion para aceptar las conexiones al back
- ajustar le header para que tenga version mobile + contexto
- ajustar main para tener los contextos en toda la app
> Ajustar reponsive del header

- src/components/atoms/Card.jsx
- src/components/molecules/RecomendadosContainer.jsx
- src/components/organisms/categories/ListProductCategory.jsx
- src/components/organisms/product/ProductDetails.jsx
- src/components/organisms/product/ProductGaleryImages.jsx
- src/components/organisms/product/ProductHeader.jsx
- src/components/organisms/product/ProductIdeas.jsx
- src/components/organisms/sections/SectionBeneficios.jsx
- src/components/organisms/sections/SectionRecomendados.jsx
- src/pages/category/Category.jsx
- src/pages/product/Product.jsx
- src/styles/_cards.scss
- src/styles/_products.scss
- src/styles/basics.scss
- src/utils/json/productosRecomendadosData.json
- Dejar Producto detalle como en figma
- Ajustar estilos de las cards
> Ajustar ultimos detalles de producto detalle

- src/components/atoms/admin/FormAgregarProducto.jsx
- Consolidé el estado del producto en un único objeto para reducir el número de hooks de estado individuales.
- Creé una función handleInputChange para manejar los cambios en los campos del formulario.
- Añadí una función validateForm para validar los campos del formulario antes de enviar.
- Simplifiqué el manejo de imágenes y añadí un botón para agregar más campos de imágenes.
- Generalmente, limpié y mejoré la estructura y la legibilidad del código.
> + Refactorizado Código de Agregar Producto

- src/components/atoms/Cards.jsx
- src/components/atoms/Modals.jsx
- src/components/atoms/admin/FormProduct.jsx
- src/components/atoms/admin/ListProducts.jsx
- src/components/atoms/form/ListImages.jsx
- src/components/molecules/admin/AdminCategories.jsx
- src/components/molecules/admin/AdminDashboard.jsx
- src/components/molecules/admin/AdminProducts.jsx
- src/components/molecules/product/ProductDetails.jsx
- src/components/molecules/product/ProductGallery.jsx
- src/components/molecules/product/ProductHeader.jsx
- src/components/molecules/product/ProductLists.jsx
- src/components/organisms/sections/SectionAdmin.jsx
- src/pages/admin/Admin.jsx
- src/styles/_modal.scss
- Card productos lista admin
- El modal maneja crear y editar aunque faltan detalles
- Formproductos para aceptar id del producto a actualizar
- Listproducts para listar los productos en el panel admin
> Listar productos, conectar modal de editar, ver producto, falta eliminar

- src/App.jsx
- src/components/atoms/Cards.jsx
- src/components/atoms/Modals.jsx
- src/components/atoms/admin/FormProduct.jsx
- src/components/atoms/admin/ListProducts.jsx
- src/components/atoms/admin/ModalDelete.jsx
- src/styles/_modal.scss
- Ajustar el form de ajustar productos con state.data
- Agregar la paginacion con los productos existente, ajustar cuando hayan mas productos
- Ajustar estilos del modal para visualizar mejor
- Agregar primeras partes para eliminar producto
> 👌🏼Agregar listar productos con editar ver y eliminar inidviduales

- src/App.jsx
- src/components/atoms/Cards.jsx
- src/components/atoms/admin/FormProduct.jsx
- src/components/atoms/admin/ModalDelete.jsx
- src/components/molecules/header/HeaderNavCategories.jsx
- src/components/molecules/header/HeaderNavUser.jsx
- src/components/molecules/product/ProductDetails.jsx
- src/components/molecules/product/ProductGallery.jsx
- src/components/organisms/lists/ListProductsCategory.jsx
- src/contexts/global.context.jsx
- src/pages/ProtectedRoute.jsx
- src/pages/category/Category.jsx
- src/pages/home/Home.jsx
- src/reducers/reducer.js
- Quitar sobrantes de App.js y conectar paginas protegidas
- Cards de productos fondo blanco y muestran imagen por defecto si no llega ninguna
- Se agrega categorias al contexto global y re ajustan los componentes que hacen uso. menos la parte de homeCategories por lo de las imagenes
- Eliminar producto luego de la solicitud de la api para eliminar pide de nuevo los productos para catualizar state.data
- HeaderNav User entiende si el usuario esta log o no
- Se crea archivo protectedroute para saber si el usuario esta logeado
- En el home se cambian unos fondos para ver como resaltan mejor las card de productos
> Crear rutas protegidas, ajustar contexto global para categorias

- docker/docker-compose.dev.yml
- src/components/atoms/Buttons.jsx
- src/components/atoms/ErrorDialog.jsx
- src/components/atoms/LoadingOverlay.jsx
- src/pages/product/Product.jsx
- src/styles/basics.scss
- Se añadio un Loader con su componente para el detalle de producto
- Se añadio un popup de Error en caso de error en el producto
- Se modifico el tamaño de los botones
> Botones, Loader y Errores en Product

- src/components/atoms/admin/FormProduct.jsx
- src/components/atoms/admin/ModalDelete.jsx
- src/contexts/global.context.jsx
- src/reducers/reducer.js
- src/styles/_modal.scss
- src/utils/js/apiRequest.js
- Sacar headers token del apiRequest original para aplicarla solo donde se necesita
- Ajustar el global context para que guarde el token
- Probar crear, editar y eliminar producto con el token
> Ajustar headers de la apiRequest

- package-lock.json
- src/components/molecules/admin/AdminDashboard.jsx
- src/components/molecules/product/ProductPolicies.jsx
- src/components/organisms/sections/SectionProducto.jsx
- src/pages/product/Product.jsx
Aún estoy mejorando algunas cosas, mientras llame a la API desde el componente, pero trabajaré para que la información venga desde el mismo objeto de la api de producto.
> Sección políticas Definitiva

- package-lock.json
- package.json
- src/components/molecules/product/ProductDetails.jsx
- src/utils/json/featuresData.json
Por ahora está con data del front, falta que se actualice un pull request del back para poder añadirlo con la data de la BD.
> 1era versión. Se añade sección de Características de Producto a la página de detalle

- src/components/atoms/admin/ModalDeleteCategory.jsx
Acomodar estilo de botón eliminar categoría
> Acomodar estilo de botón eliminar categoría

- src/components/atoms/Modals.jsx
- src/components/atoms/admin/ListCategories.jsx
- src/components/atoms/admin/ListProducts.jsx
- src/components/atoms/header/NavUser.jsx
- src/components/atoms/search/SearchCategory.jsx
- src/components/atoms/search/SearchDate.jsx
- src/components/atoms/search/SearchSuggestions.jsx
- src/components/atoms/search/SearchText.jsx
- src/components/molecules/home/HomeSearch.jsx
- src/components/molecules/home/HomeSearch2.jsx
- src/contexts/global.context.jsx
- src/pages/home/Home.jsx
- src/pages/product/Products.jsx
- src/reducers/reducer.js
- src/styles/_search.scss
- src/utils/js/debounce.js
- Ajustado buscador para que en mobile se comporte como modal
- Ajustar las diferentes partes del buscador
> 👌🏼Buscador ajustado en gran parte

- src/contexts/global.context.jsx
Ajustar el boton de salir de la herramienta
> Ajustado el logout de la app

- src/components/atoms/user/MiPerfil.jsx
- src/contexts/global.context.jsx
- src/reducers/reducer.js
- Ajustar el manejo de token
- Contexto global
- Reducers
> 🤘🏼Ajustar refresco de token, context-global y reducers

- src/contexts/global.context.jsx
- src/utils/js/apiRequest.js
- Cambios en el apirequest y contexto global para el token refresh
- El token se refresca si al momento de realizar la peticion esta no se puede realizar por token vencido
> 🤘🏼Refresh token

- src/components/atoms/header/NavUser.jsx
- src/components/atoms/user/AvatarUser.jsx
- src/components/atoms/user/MiPerfil.jsx
- src/components/molecules/header/HeaderNavUser.jsx
- src/contexts/global.context.jsx
- src/reducers/reducer.js
- src/utils/js/getNameInitials.js
- src/utils/routes.js
- Separar la logica del avatar user para poderlo llamar de diferentes componentes
- Creacion del componente AvatarUser
- En mi perfil simplificar los llamados a la api, trayenco la indo del state.user
- Crear logica js para tomar solo las iniciales del nombre
- Terminar de ajustar el archivo de rutas
> 🤘🏼Trabajar en el header user con las iniciales del nombre

- src/components/atoms/admin/category/FeatureInput.jsx
- src/components/atoms/admin/category/FormCategory.jsx
- src/components/atoms/admin/category/StickerModal.jsx
- src/components/molecules/product/ProductDetails.jsx
- src/utils/json/iconData.json
Actualización de iconos en características de categoría
> Actualización de iconos en características de categoría

- src/components/atoms/admin/category/FeatureInput.jsx
- src/components/atoms/admin/category/FormCategory.jsx
Corrección de Errores en iconos de categoría
> Corrección de Errores en iconos de categoría

- src/components/molecules/user/UserMenu.jsx
- src/components/organisms/SidebarMenu.jsx
- src/pages/admin/Admin.jsx
- src/pages/user/User.jsx
- src/styles/_admin.scss
- src/utils/routes.js
- Probar variacion de menu combinado que valida si soy o no admin
- Falta agregar logica para los usuarios editores
> 🤘🏼Menu combinado admin user

- src/components/atoms/admin/product/FeatureSelection.jsx
- src/components/atoms/admin/product/FormProduct.jsx
Se agregan Features a los productos.
> Se agregan Features a los productos. Depende de una actualización de back pendiente por subir.

- src/components/atoms/admin/category/FeatureInput.jsx
- src/components/atoms/admin/category/FormCategory.jsx
- src/components/atoms/admin/category/PolicyInput.jsx
- src/components/atoms/admin/category/StandardInput.jsx
- src/components/atoms/admin/product/FeatureSelection.jsx
- src/components/atoms/admin/product/FormProduct.jsx
- src/components/molecules/product/ProductDetails.jsx
Manejo de Errores en Category y Product
> Manejo de Errores en Category y Product

- src/components/atoms/admin/product/FeatureSelection.jsx
> Camio Pendiente en Product

- src/components/atoms/Cards.jsx
- src/components/molecules/home/HomeRecommended.jsx
- src/components/molecules/user/UserFavoritos.jsx
- src/components/organisms/SidebarMenu.jsx
- src/contexts/global.context.jsx
- src/reducers/reducer.js
- src/styles/_cards.scss
- Ajustar card de productos
- Crear una card de producto que permita agregar y quitar favoritos
- Listar favoritos en un carrusel + mensaje si no hay favs seleccionados
> 🤘🏼Ajustar fav mostrar y cambiar si estoy log, listar en carrusel

- src/components/atoms/Cards.jsx
- src/components/atoms/admin/permisos/ListUsers.jsx
- src/components/atoms/header/NavUser.jsx
- src/components/atoms/user/MiPerfil.jsx
- src/components/organisms/SidebarMenu.jsx
- src/contexts/global.context.jsx
- src/reducers/reducer.js
- Manejo del rol de los usuarios desde la cuenta de Admin
- Conectar lista de usuarios desde la API
- Ajustar que el usuario diga que rol tiene  en el perfil
- Ajustar el contexto y el reducer
> 🤘🏼Ajuste de Rol de los usuarios

- src/components/molecules/product/ProductDetails.jsx
- src/components/molecules/product/ProductHeader.jsx
- src/components/molecules/share/ShareButton.jsx
- Ajustar boton de favs en detalle producto
> 👌🏼Ajustar boton de fav y subir compartir

- src/components/molecules/product/ProductAvailability.jsx
- Ajuste para ver resercas pasadas
> 🤞Ajustar calendario de producto detalle
